### ISSUE TITLE
Using String ID and getting None after generating ID on MongoDB side

### ISSUE THREAD

**Issue by dkarpenko** [novus/salat#144]
I'm trying to design _clean_ case classes without any references to `ObjectId` and MongoDB. Ideally, to be able to have `String` ids automatically generated on MongoDB side and returned after `insert`. For example:

```scala
case class Bar(x: String, _id: Option[String] = None)

val bar = Bar(x = "bar")
val id = barDao.insert(bar)

// id 54e5f6df5b66bbb6f894f7fe
```

But I've faced with an issue related to [getting the value](https://github.com/novus/salat/blob/master/salat-core/src/main/scala/com/novus/salat/dao/SalatDAO.scala#L308) of `_id` in proper type (`String` in my case) -  at that point `_id -> ObjectId(....)` result is available in returned object. Example of code and returned output is available bellow. 

Could anybody suggest me how can I use `String` type for ids in the same way as `ObjectId` (get Ids of documents after insertion)?

```scala
  case class Bar(x: String, _id: Option[ObjectId] = None)
  case class Foo(x: String, _id: Option[String] = None)
  //  ...

  import com.novus.salat.global._
  private val connection: MongoDB = MongoConnection(MongoURI("mongodb://hostname:27017/"))("db-name")
  object FooDAO extends SalatDAO[Foo, String](collection = connection("test_collection_foo"))
  object BarDAO extends SalatDAO[Bar, ObjectId](collection = connection("test_collection_bar"))

  //  ...
  def fooInfo(id: Option[String], alpha: Foo, count: Long) = {
    println("***********************")
    println("[Foo] Count: " + count)
    println("[Foo] Returned Id: " + id)
    println("[Foo] Object: " + alpha)
  }

  def barInfo(id: Option[ObjectId], alpha: Bar, count: Long) = {
    println("***********************")
    println("[Bar] Count: " + count)
    println("[Bar] Returned Id: " + id)
    println("[Bar] Object: " + alpha)
  }

  val foo1 = Foo(_id = Some("a"), x = "foo1")
  val _id1 = FooDAO.insert(foo1)
  fooInfo(_id1, foo1,FooDAO.count())

  val foo2 = Foo(x = "foo2")
  val _id2 = FooDAO.insert(foo2)
  fooInfo(_id2, foo2,FooDAO.count())


  println("#####################")

  val bar1 = Bar(_id = Some(new ObjectId), x = "bar1")
  val _barId1 = BarDAO.insert(bar1)
  barInfo(_barId1, bar1,BarDAO.count())


  val bar2 = Bar(x = "bar2")
  val _barId2 = BarDAO.insert(bar2)
  barInfo(_barId2, bar2,BarDAO.count())


```

Output:
```
***********************
[Foo] Count: 1
[Foo] Returned Id: Some(a)
[Foo] Object: Foo(foo1,Some(a))
***********************
[Foo] Count: 2
[Foo] Returned Id: None
[Foo] Object: Foo(foo2,None)
#####################
***********************
[Bar] Count: 1
[Bar] Returned Id: Some(54e7746f0598bf10ebf2934b)
[Bar] Object: Bar(bar1,Some(54e7746f0598bf10ebf2934b))
***********************
[Bar] Count: 2
[Bar] Returned Id: Some(54e7746f0598bf10ebf2934c)
[Bar] Object: Bar(bar2,None)
```

**Comment by rktoomey** [comment]
@dkarpenko: don't make it an `Option`, just assign the `_id: ObjectId = new ObjectId` yourself. 

While mongo-java-driver will assign a value to the `_id` field if you fail to do so yourself, it's not like a database generated id sequence.  This is done _before_ the document is inserted in the collection.

**Comment by dkarpenko** [comment]
The issue/question is mostly about returning ID in proper type when it was generated by driver. 
I understand that converting ObjectId to Int/Long is not an obvious operation, but, at least, ability to return String representation would be great..

Here is a state of dbo object after inserting new document: `_id` has a value of `ObjectId` type, but `dbo.getAs[ID]("_id")` fails to return `String` value (and it's clear why after looking into details of its implementation). 
![screenshot 2015-02-22 19 48 44](https://cloud.githubusercontent.com/assets/276681/6319830/7fec71ea-badc-11e4-9b4d-b7be07981add.png)

Looks it's just a question of converting `ObjectId` to `String`. I'm thinking about having smth like 0c68a3f3b291ace979eceb4b509a642e77c025d0

@rktoomey, what do you think about it?

**Comment by rktoomey** [comment]
I'm confused - does the toString method on ObjectId somehow fall to fulfill your requirement?

**Comment by dkarpenko** [comment]
My limitation is that core layer of application knows nothing about ObjectId, Salat and MongoDB in general: models are simple as `case class Foo(x: String, id: Option[String] = None)` and have `String` or `Option[String]` as id attribute. 

I have very simple DAO trait with operation `insert(entity: E): Option[String]` for all my models and was trying to use implementation from `SalatDAO` for this function.
